### ISSUE TITLE
phpstan version

### ISSUE THREAD

**Issue by PhilippHandle** [noximo/PHPStan-FileOutput#8]
phpStan changed version and is no longer 0.12.x.
so can you change the required version to something like 1.2.x?

**Comment by noximo** [comment]
Hi, I no longer use this tool myself but feel free to update it, I'll happily merge it in afterwards.

**Comment by PhilippHandle** [comment]
Done

**Comment by noximo** [comment]
Thanks. Updated. The possible depnedency problem can be dealt with later.
